apiVersion: apps/v1
kind: Deployment
metadata:
    name: cli-peer0-dealer
spec:
    selector:
        matchLabels:
            name: cli-peer0-dealer
    template:
        metadata:
            labels:
                name: cli-peer0-dealer
        spec:
            volumes:
                - name: fabricfiles
                  persistentVolumeClaim:
                      claimName: mypvc

            containers:
                - name: cli-peer0-dealer
                  stdin: true
                  tty: true
                  resources:
                        limits:
                          memory: "300Mi"
                          cpu: "200m"
                        requests:
                          memory: "200Mi"
                          cpu: "90m"
                  image: hyperledger/fabric-tools:2.2.2
                  workingDir: /
                  env:
                      - name: ORDERER_CA
                        value: /organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/msp/tlscacerts/tlsca.auto.com-cert.pem

                      - name: CORE_PEER_ADDRESS
                        value: peer0-dealer:7051
                      - name: CORE_PEER_ID
                        value: cli.peer0.dealer.auto.com
                      - name: CORE_PEER_LOCALMSPID
                        value: DealerMSP
                      - name: CORE_PEER_MSPCONFIGPATH
                        value: /organizations/peerOrganizations/dealer.auto.com/users/Admin@dealer.auto.com/msp
                      - name: CORE_PEER_TLS_CERT_FILE
                        value: /organizations/peerOrganizations/dealer.auto.com/peers/peer0.dealer.auto.com/tls/server.crt
                      - name: CORE_PEER_TLS_ENABLED
                        value: "true"
                      - name: CORE_PEER_TLS_KEY_FILE
                        value: /organizations/peerOrganizations/dealer.auto.com/peers/peer0.dealer.auto.com/tls/server.key
                      - name: CORE_PEER_TLS_ROOTCERT_FILE
                        value: /organizations/peerOrganizations/dealer.auto.com/peers/peer0.dealer.auto.com/tls/ca.crt
                      - name: FABRIC_LOGGING_SPEC
                        value: ERROR
                      - name: GOPATH
                        value: /opt/gopath
                      - name: SYS_CHANNEL
                        value: system-channel
                      - name: CORE_CHAINCODE_BUILDER
                        value: hyperledger/fabric-ccenv:1.4.8
                      - name: FABRIC_LOGGING_SPEC
                        value: DEBUG
                  volumeMounts:
                      - mountPath: /configtx
                        name: fabricfiles
                        subPath: configtx
                      - mountPath: /organizations
                        name: fabricfiles
                        subPath: organizations
                      - mountPath: /channel-artifacts
                        name: fabricfiles
                        subPath: channel-artifacts
                      - mountPath: /scripts
                        name: fabricfiles
                        subPath: scripts
                      - mountPath: /opt/gopath/src/github.com/chaincode
                        name: fabricfiles
                        subPath: chaincode
